### PR TITLE
Do not remove .config folder

### PR DESCRIPTION
**Pull request by msarahan**
this folder contains config from a wide variety of things, and should not be removed.

Related to #3

### CODE REVIEW

**Comment by ccordoba12** [comment]
The configuration directories for Spyder (since Spyder 3) are placed in `.config`: `.config/spyder` (PY2) and `.config/spyder-py3` (PY3)

**Comment by ccordoba12** [comment]
So I think we should take care of removing those here too :-)

**Comment by msarahan** [comment]
It is not immediately clear to me that the logic here supports subfolders.  I'm more concerned about stopping the potential terrible damage that we're causing people right now.  Do you mind adding those folders and verifying that they work in a separate PR?

**Comment by ccordoba12** [comment]
Yeah, no problem.

**Pull request merged**
